#!/usr/bin/env bash
OUTPUT_DIR="output"
V="$(git describe --tags)"
TMP_OUT="/tmp/$V"

rm -rf "$OUTPUT_DIR"
./scripts/build
tar -czf "$TMP_OUT.tgz" "$OUTPUT_DIR/"
zip "$TMP_OUT.zip" -r "$OUTPUT_DIR/" 
mv "$TMP_OUT.tgz" "$OUTPUT_DIR/$V.tgz"
mv "$TMP_OUT.zip" "$OUTPUT_DIR/$V.zip"
